#!/bin/bash

set -e

if [ -z "$1" ]; then
  echo "Usage: ./release 1.0.0";
  exit 1;
fi;

VERSION="$1"
TAG="$VERSION"

sed -e "s/Version:.*/Version: $TAG/" -e "s/MEMBERFUL_VERSION', '[^']*'/MEMBERFUL_VERSION', '$VERSION'/" -i "" memberful-wp.php
sed -e "s/Stable tag:.*/Stable tag: $TAG/" -i "" readme.txt

"${EDITOR:-vi}" readme.txt

git diff

read

git commit -aem "Changing stable version number to $VERSION"

git tag "$TAG"

git checkout master

git reset --hard "$TAG"

git push --all origin
git push --tags origin

SVNUSER=memberful PLUGINSLUG=memberful-wp ./deploy.sh
