#!/bin/bash

set -e

if [ -z "$1" ]; then
  echo "Usage: ./release 1.0.0";
  exit 1;
fi;

VERSION="$1"
TAG="$VERSION"

sed -re "s/Version:[^\\n]+/Version: $TAG/" -e "s/MEMBERFUL_VERSION', '[^']*'/MEMBERFUL_VERSION', '$VERSION'/" -i memberful-wp.php
sed -re "s/Stable tag:[^\\n]+/Stable tag: $TAG/" -i readme.txt

"${EDITOR:-vi}" readme.txt

git diff

read

git commit -aem "Changing stable version number to $VERSION"

git tag "$TAG"

git checkout master

git reset --hard "$TAG"

git push --all origin
git push --tags origin

SVNUSER=memberful PLUGINSLUG=memberful-wp ./deploy.sh
